### PR TITLE
Fix extra space under img

### PR DESCRIPTION
**Pull request by sunyiming**

### CODE REVIEW

**Comment by amphineko** [comment]
Hello, thanks for your contribution.

Could you provide me a live example that reflects your changes?

**Comment by sunyiming** [comment]
Take [this page](https://futa.moe/amphineko/) for an example. On Chrome 92, the size of `<picture>` element is 329.6 x 333.6 px, but the size of its child element `` is 329.6 x 329.6 px, which leave space under the `` element. It will be more obviously if you change the avatar to a black image.

I think adding `vertical-align` attribute to `` element may fix this bug.

**Comment by amphineko** [comment]
What do you think if it's better to fix using flex.

**Comment by sunyiming** [comment]
It also works.

I found stackoverflow discussion about it: https://stackoverflow.com/questions/5804256/image-inside-div-has-extra-space-below-the-image

**Pull request closed without merging**
